### ISSUE TITLE
Failed to build kn-plugin-admin

### ISSUE THREAD

**Issue by chaozbj** [knative-sandbox/kn-plugin-admin#10]
When we run `release.sh` or run `go build` in cmd folder, we got the following error:
```
../pkg/command/registry/list.go:27:2: cannot find package "." in:
	/Users/chao/Workspace/Code/github.com/knative/kn-plugin-admin/vendor/knative.dev/client-contrib/plugins/admin/pkg
```

I guess this is caused by **module renaming**, we may missed the codes in ongoing RP when we changed the module name. I will fix it soon.

**Comment by zhanggbj** [comment]
@chaozbj This is caused by the lastest two merged PR 1) import path change 2) registry list (user old path)
I'm raising PR now.

**Comment by chaozbj** [comment]
@zhanggbj Sorry, I just saw you have a PR to address it. I will close my RP.

**Comment by zhanggbj** [comment]
@chaozbj No worries. I'm trying to unblock others, but we need to wait for another review to merge it.

**Comment by zhanggbj** [comment]
@chaozbj this is fixed, would you please help to close it. Thanks!
