### ISSUE TITLE
As a developer, I want to setup test-infra for kn-plugin-admin

### ISSUE THREAD

**Issue by zhanggbj** [knative-sandbox/kn-plugin-admin#13]

**Comment by zhanggbj** [comment]
@zyjiaobj is working on this, to setup test-infra for kn-plugin-admin.
This is important, especially we need to avoid issues like #10

**Comment by maximilien** [comment]
Thank you @zhanggbj and @zyjiaobj

**Comment by zhanggbj** [comment]
FYI. This is pending on a PR from @evankanderson https://github.com/knative/test-infra/pull/2514

**Comment by rhuss** [comment]
@zhanggbj I think we can close this issue, as the CI has been setup now ?

**Comment by zhanggbj** [comment]
/assign @navidshaikh 
Sure, Navid have covered test-infra in his PR, close it!
CC @rhuss
