### ISSUE TITLE
As a Knative administrator, I want to get logging access url and other info easily

### ISSUE THREAD

**Issue by chaozbj** [knative-sandbox/kn-plugin-admin#33]
Knative administrator usually need to access logging for debugging purpose. The kn-admin plugin will start a proxy in background and provide the access url.

```shell
$ kn admin obv logging get --endpoint
Local proxy started.
Access url: http://localhost:8001/api/v1/namespaces/knative-monitoring/services/kibana-logging/proxy/app/kibana
```

**Comment by navidshaikh** [comment]
how about `kn admin obv logging start-proxy` ? 

The command should reflect the operation while the URL can the result for the successful operation. Following how we do `kn service create`.
cc: @duglin

**Comment by chaozbj** [comment]
@navidshaikh Thanks for your comments, we will consider to use a meaningful name for this command.
