### ISSUE TITLE
As a kn-admin developer, I want to ensure readiness for a formal release

### ISSUE THREAD

**Issue by zhanggbj** [knative-sandbox/kn-plugin-admin#36]
Based on the discussion for kn plugin release, need to double check and make sure readiness for a formal release

https://knative.slack.com/archives/CE4MVFVAQ/p1607440768179900

1. “Downstream Test”: https://github.com/knative/pkg/blob/master/.github/workflows/knative-downstream.yaml (make sure you don’t break your downstream deps!)
2. “knobots / repos.yaml”: https://github.com/knative-sandbox/knobots/blob/master/repos.yaml (regularly pull in your downstream deps!)
3. “Releasability” (synced via knobots to all configured repos): https://github.com/knative-sandbox/.github/blob/a88c106c1d8313ddd91708acc14b5499f380908f/workflow-templates/knative-releasability.yaml (check whether you are “ready” to release based on your knative deps)

**Comment by zhanggbj** [comment]
/assign @12345lcr 
Per offline talk, Chenrui will take care of it, thanks!

Please also help to fill up https://github.com/knative-sandbox/kn-plugin-admin/community

- [ ] Code of conduct
- [ ] Issue templates
- [ ] Repository admins accept content reports

**Comment by 12345lcr** [comment]
Downstream unit test failed. Because in `time` package the error messages have changed when bumping go version to 1.15 from 1.14.
https://github.com/knative/pkg/pull/1983/checks?check_run_id=1687803705

Should be fixed after merging https://github.com/knative-sandbox/kn-plugin-admin/pull/30.

**Comment by zhanggbj** [comment]
UT error is fixed and go version has been bumped to 1.15. FYI.
